## GUT test: cross-platform AES vectors for ss-godot ↔ ss-unity interop.
##
## Verifies that `AesHelper` produces byte-for-byte identical ciphertext to
## the upstream Unity SaiEncryption.cs for a fixed set of vectors. Expected
## bytes were generated by two independent references (Python `cryptography`
## and OpenSSL 3.2.4 CLI), which agreed exactly. See tests/aes_vectors.md.
##
## Run with:
##   godot --headless --path . -s addons/gut/gut_cmdln.gd \
##       -gtest=tests/unit/test_aes_helper.gd -gexit
extends GutTest

const AesHelper := preload("res://addons/sai_services/util/aes_helper.gd")

# ---- Derived key/IV for default-passphrase vectors (set A) ------------------

const DEFAULT_KEY_HEX := "53616947616d65323032365365637572654b6579466f72456e6372797074696f"
const DEFAULT_IV_HEX := "53616947616d65323032365365637572"

# ---- Fixed key/IV for raw-API vectors (set B) -------------------------------

const FIXED_KEY_HEX := "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
const FIXED_IV_HEX := "0f0e0d0c0b0a09080706050403020100"


static func _hex_to_bytes(hex: String) -> PackedByteArray:
	var out := PackedByteArray()
	var n := hex.length()
	assert(n % 2 == 0)
	var i := 0
	while i < n:
		out.append(hex.substr(i, 2).hex_to_int())
		i += 2
	return out


static func _bytes_to_hex(b: PackedByteArray) -> String:
	var out := ""
	for byte in b:
		out += "%02x" % byte
	return out


# ---- Set A: default passphrase ----------------------------------------------


func test_default_passphrase_derivation_matches_csharp() -> void:
	# Sanity: confirm the helper's internal key/IV derivation matches the
	# C# `Array.Copy(passphraseBytes, key, Math.Min(...))` construction.
	var sample_plain := "hello world"
	# We can't read _derive_default_key directly (static private), so we infer
	# via known ciphertext: if that ciphertext is correct, derivation is correct.
	var got := AesHelper.encrypt_with_default_passphrase(sample_plain)
	assert_eq(
		got,
		"9oHnTIaE82JI92J35spSSQ==",
		"default-passphrase 'hello world' ciphertext mismatch — key/IV derivation drifted from C#?"
	)


func test_default_passphrase_empty_short_circuits() -> void:
	# Mirrors `if (string.IsNullOrEmpty(plainText)) return string.Empty;`
	assert_eq(AesHelper.encrypt_with_default_passphrase(""), "")
	assert_eq(AesHelper.decrypt_with_default_passphrase(""), "")


func test_default_passphrase_hello_world() -> void:
	var expected := "9oHnTIaE82JI92J35spSSQ=="
	var got := AesHelper.encrypt_with_default_passphrase("hello world")
	assert_eq(got, expected)
	assert_eq(AesHelper.decrypt_with_default_passphrase(expected), "hello world")


func test_default_passphrase_multiblock() -> void:
	var plain := "The quick brown fox jumps over the lazy dog."
	var expected := "65XbAiIQ4ejK63nBNX67eaw85m4KTp8v4XaGFtUk1RVdOOvYLBhHHOcCyb0higZw"
	assert_eq(AesHelper.encrypt_with_default_passphrase(plain), expected)
	assert_eq(AesHelper.decrypt_with_default_passphrase(expected), plain)


func test_default_passphrase_utf8_nonascii() -> void:
	# Note: source string contains "café 🎮" (U+00E9 and U+1F3AE).
	var plain := "café 🎮"
	var expected := "W2AqNZj/AHWp5gtJjMjiZQ=="
	assert_eq(AesHelper.encrypt_with_default_passphrase(plain), expected)
	assert_eq(AesHelper.decrypt_with_default_passphrase(expected), plain)


func test_default_passphrase_exact_block_size() -> void:
	# 16 bytes — forces PKCS7 to add a full extra padding block.
	var plain := "YELLOW SUBMARINE"
	var expected := "7wesbJvaHXsc8QVWaoS0Wa0PtI0tzcMt3DEiFG3IbRk="
	assert_eq(AesHelper.encrypt_with_default_passphrase(plain), expected)
	assert_eq(AesHelper.decrypt_with_default_passphrase(expected), plain)


# ---- Set B: raw encrypt()/decrypt() with fixed key/IV -----------------------


func _assert_raw_vector(plain_bytes: PackedByteArray, expected_hex: String) -> void:
	var key := _hex_to_bytes(FIXED_KEY_HEX)
	var iv := _hex_to_bytes(FIXED_IV_HEX)
	var cipher := AesHelper.encrypt(plain_bytes, key, iv)
	var got_hex := _bytes_to_hex(cipher)
	assert_eq(
		got_hex,
		expected_hex,
		"raw encrypt() byte mismatch for plaintext %s" % plain_bytes.hex_encode()
	)
	# round-trip
	var decrypted := AesHelper.decrypt(cipher, key, iv)
	assert_eq(
		_bytes_to_hex(decrypted),
		_bytes_to_hex(plain_bytes),
		"raw decrypt() failed to recover plaintext"
	)


func test_raw_empty() -> void:
	_assert_raw_vector(PackedByteArray(), "daf015b15d25544a9510b84fb6d94efd")


func test_raw_hello_world() -> void:
	_assert_raw_vector("hello world".to_utf8_buffer(), "7e9a97128ef0b4a45935313b08430fda")


func test_raw_multiblock() -> void:
	_assert_raw_vector(
		"The quick brown fox jumps over the lazy dog.".to_utf8_buffer(),
		"925c81ee81fae7d66040fade898963245afeab7af7697a0762fe3f72ebfe8a356d6c722d7f08f7c5d45a6db04d8606f3"
	)


func test_raw_utf8_nonascii() -> void:
	_assert_raw_vector("café 🎮".to_utf8_buffer(), "8e3b135e9c503d50131bd92c54661c38")


func test_raw_exact_block_size() -> void:
	_assert_raw_vector(
		"YELLOW SUBMARINE".to_utf8_buffer(),
		"134deee4fb08e5e807b242cc549520fa416bd663fb5effca9f85f9dcc6b305f5"
	)


# ---- Round-trip with random inputs (catches IV-handling regressions) --------


func test_random_round_trip() -> void:
	# 32 randomized round-trips with varied plaintext lengths covering every
	# residue class mod the AES block size.
	var rng := RandomNumberGenerator.new()
	rng.seed = 0xC0FFEE  # deterministic-but-arbitrary so failures reproduce
	for trial in 32:
		var plain_len: int = rng.randi_range(0, 64)
		var plain := PackedByteArray()
		plain.resize(plain_len)
		for i in plain_len:
			plain[i] = rng.randi() & 0xff

		var key := PackedByteArray()
		key.resize(32)
		for i in 32:
			key[i] = rng.randi() & 0xff

		var iv := PackedByteArray()
		iv.resize(16)
		for i in 16:
			iv[i] = rng.randi() & 0xff

		var cipher := AesHelper.encrypt(plain, key, iv)
		assert_true(cipher.size() > 0, "encrypt returned empty (trial %d)" % trial)
		assert_eq(cipher.size() % 16, 0, "ciphertext not block-aligned (trial %d)" % trial)
		var decrypted := AesHelper.decrypt(cipher, key, iv)
		assert_eq(
			_bytes_to_hex(decrypted),
			_bytes_to_hex(plain),
			"round-trip mismatch on trial %d (plain_len=%d)" % [trial, plain_len]
		)


# ---- Negative tests (defensive — make sure validation still fires) ----------


func test_rejects_bad_iv_length() -> void:
	var key := _hex_to_bytes(FIXED_KEY_HEX)
	var iv := PackedByteArray()
	iv.resize(8)  # wrong size on purpose
	var out := AesHelper.encrypt("x".to_utf8_buffer(), key, iv)
	assert_eq(out.size(), 0, "encrypt with bad IV size should return empty PackedByteArray")


func test_rejects_bad_key_length() -> void:
	var key := PackedByteArray()
	key.resize(20)  # not 16/24/32
	var iv := _hex_to_bytes(FIXED_IV_HEX)
	var out := AesHelper.encrypt("x".to_utf8_buffer(), key, iv)
	assert_eq(out.size(), 0, "encrypt with bad key size should return empty PackedByteArray")
